version: '3'
services:
  app-client:
    restart: always
    build:
      context: mentor-on-demand-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app-server

  app-server:
    restart: always
    build:
      context: mentor-on-demand-api 
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
