pipeline {
  tools {
    maven 'Maven 3.3.9'
    jdk 'jdk8'
  }
  stages {

    stage('Build') {
        steps {
            sh 'mvn -Dmaven.test.skip=true clean install'
        }
    }

    stage('Tests') {
        steps {
            sh 'mvn test'
        }
        post {
          success {
            junit 'target/surefire-reports/**/*.xml'
          }
        }
    }
    
  }
}
